-- ============================================================================
-- 99_RESET.SQL — Reset Sukuk Portfolio Analytics to clean demo state
-- ============================================================================
USE DATABASE ISLAMIC_SUKUK_INDONESIA;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_MARKET_DATA SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REVALUE_PORTFOLIO SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST_YIELDS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.PORTFOLIO_SUMMARY REFRESH;
ALTER DYNAMIC TABLE CURATED.YIELD_CURVES REFRESH;
ALTER DYNAMIC TABLE CURATED.ISSUER_RISK REFRESH;
ALTER DYNAMIC TABLE CURATED.MATURITY_LADDER REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM ISLAMIC_SUKUK_INDONESIA.RAW.SUKUK_HOLDINGS → 800
-- SELECT COUNT(*) FROM ISLAMIC_SUKUK_INDONESIA.RAW.VALUATIONS → 20000
-- SELECT COUNT(*) FROM ISLAMIC_SUKUK_INDONESIA.RAW.MARKET_DATA → 80000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_FORECAST_YIELDS RESUME;
ALTER TASK IF EXISTS APP.TASK_REVALUE_PORTFOLIO RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_MARKET_DATA RESUME;
